
// This file has been generated by the GUI designer. Do not modify.
namespace Hegoburu.Presentation.Core.Desktop.Gtk.Demo.UI.Views
{
	public partial class MainWidgetView
	{
		private global::Gtk.HPaned hpaned1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Hegoburu.Presentation.Core.Desktop.Gtk.Demo.UI.Views.MainWidgetView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Hegoburu.Presentation.Core.Desktop.Gtk.Demo.UI.Views.MainWidgetView";
			// Container child Hegoburu.Presentation.Core.Desktop.Gtk.Demo.UI.Views.MainWidgetView.Gtk.Container+ContainerChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 169;
			this.Add (this.hpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
