
// This file has been generated by the GUI designer. Do not modify.
namespace Hegoburu.Presentation.Core.Desktop.Gtk.Demo.UI.Views.Persona
{
	public partial class PersonaListWidgetView
	{
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.IconView ivwPersonas;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button btnAgregar;
		private global::Gtk.Button btnEditar;
		private global::Gtk.Button btnBorrar;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Hegoburu.Presentation.Core.Desktop.Gtk.Demo.UI.Views.Persona.PersonaListWidgetView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Hegoburu.Presentation.Core.Desktop.Gtk.Demo.UI.Views.Persona.PersonaListWidgetView";
			// Container child Hegoburu.Presentation.Core.Desktop.Gtk.Demo.UI.Views.Persona.PersonaListWidgetView.Gtk.Container+ContainerChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 245;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.ivwPersonas = new global::Gtk.IconView ();
			this.ivwPersonas.CanFocus = true;
			this.ivwPersonas.Name = "ivwPersonas";
			this.vpaned1.Add (this.ivwPersonas);
			global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.ivwPersonas]));
			w1.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnAgregar = new global::Gtk.Button ();
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString ("Agregar");
			this.hbuttonbox1.Add (this.btnAgregar);
			global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnAgregar]));
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnEditar = new global::Gtk.Button ();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			this.btnEditar.Label = global::Mono.Unix.Catalog.GetString ("Editar");
			this.hbuttonbox1.Add (this.btnEditar);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnEditar]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnBorrar = new global::Gtk.Button ();
			this.btnBorrar.CanFocus = true;
			this.btnBorrar.Name = "btnBorrar";
			this.btnBorrar.UseUnderline = true;
			this.btnBorrar.Label = global::Mono.Unix.Catalog.GetString ("Borrar");
			this.hbuttonbox1.Add (this.btnBorrar);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnBorrar]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vpaned1.Add (this.hbuttonbox1);
			this.Add (this.vpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnAgregar.Clicked += new global::System.EventHandler (this.OnBtnAgregarClicked);
		}
	}
}
