
// This file has been generated by the GUI designer. Do not modify.
namespace Hegoburu.Presentation.Core.Desktop.Gtk.Demo.UI.Views.Persona
{
	public partial class lala
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Hegoburu.Presentation.Core.Desktop.Gtk.Demo.UI.Views.Persona.lala
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Hegoburu.Presentation.Core.Desktop.Gtk.Demo.UI.Views.Persona.lala";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
